# Generated by Django 4.2.1 on 2023-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_person_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='test_field',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
