# Generated by Django 4.2 on 2023-04-10 15:49

import MyPlantApp.validators.profile_validators.profile_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPlantApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmodel',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(max_length=20, validators=[MyPlantApp.validators.profile_validators.profile_validators.check_for_capital_first_letter], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(max_length=20, validators=[MyPlantApp.validators.profile_validators.profile_validators.check_for_capital_first_letter], verbose_name='Last Name'),
        ),
    ]
