# Generated by Django 4.2 on 2023-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPlantApp', '0002_alter_plantmodel_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
