# Generated by Django 4.2.1 on 2023-06-11 19:11

import CarCollectionApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SPORTS CAR', 'Sports Car'), ('PICKUP', 'Pickup'), ('CROSSOVER', 'Crossover'), ('MINIBUS', 'Minibus'), ('OTHER', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.PositiveIntegerField(validators=[CarCollectionApp.models.validate_correct_model_year])),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('price', models.FloatField(validators=[CarCollectionApp.models.validate_price_is_not_under_one])),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[CarCollectionApp.models.min_length_validator])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(validators=[CarCollectionApp.models.validate_min_age])),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(blank=True, default='', max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=30, verbose_name='Last Name')),
                ('profile_picture', models.URLField(blank=True, default='', verbose_name='Profile Picture')),
            ],
        ),
    ]
